server:
  port: 8080

spring:
  application:
    name: web-admin
  config:
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-domain.yml

  profiles:
    active: local

  thymeleaf:
    cache: false

  devtools:
    restart:
      additional-paths:
      - ../cores/build/classes/java/main
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

logging:
  config: classpath:logback-spring.xml

keycloak:
  server-url: http://localhost:8085
  realm: theloungemembers
  clientId: web-admin
  clientSecret: ybgftPoDs9uocOeBfqGv6H4N9Xu1BEpQ