plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation project(':core-common')
    implementation project(':core-model')
    implementation project(':core-web')
    implementation project(':core-lounge')

    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
}