plugins {
    id 'java-library'
}

dependencies {
    implementation project(':core-common')
//    implementation 'org.mapstruct:mapstruct:1.6.0'
//    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.0'
//    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'


    implementation 'com.google.guava:guava:33.2.1-jre'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.17.2'

}

//bootJar {
//    enabled = false
//}

jar {
    enabled = true
}