plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':web-admin')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

bootJar {
    enabled = true
    archiveFileName = 'web-integrated.jar'
}

jar {
    enabled = false
}